### PR TITLE
Restore quaternion utilities in utils.h

### PR DESCRIPTION
**Pull request by xEnVrE**
In #89, `utils.h` has been made a header-only utility file after recovering some old commits from `cfantacci/bayes-filters-lib`.

During the cherry-picking operation I didn't realize that, meanwhile, `utils.cpp` have been populated with utilities to handle quaternions and rotation vectors. Since these methods are not templated I am restoring build of `src/BayesFilters/src/utils.cpp` because at the moment `utils.h` contain the signature of these methods but their implementation is not compiled.

These methods are using `Eigen::Ref` so they are versatile enough to accept, e.g., blocks as input however they are constrained to data structures containing doubles. Since we are using doubles in this library, and not floats, and since I think it makes less sense to extend quaternion utilities to non-doubles I would avoid having a templated version of these methods. Of course, if necessary, I can make it to have a unique header-only `utils.h`.

In this PR I also fix some typos in `bfl::utils::quaternion_to_rotation_vector()` and `rotation_vector_to_quaternion()`.

### CODE REVIEW

**Comment by claudiofantacci** [comment]
I would honestly go for an header-only template library 😄
If it is reasonable/makes sense, we can assert when a type is not a float/double (something like [this](https://stackoverflow.com/questions/874298/c-templates-that-accept-only-certain-types#)).
WDYT?

**Comment by xEnVrE** [comment]
Thank you! I'll take a look at the link and update the PR.

**Comment by xEnVrE** [comment]
I have re-implemented all the quaternion utilities as template methods.

Also added a test and updated `CHANGELOG.md` accordingly.

To conclude, I fixed the style of comments in some older methods in `utils.h`.

@claudiofantacci

**Review by claudiofantacci — APPROVED** [review]
LGTM!

**Pull request merged**
